services:
  database:
    image: postgres:17
    environment:
      POSTGRES_DB: teste
      POSTGRES_USER: user
      POSTGRES_PASSWORD: teste
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_nest
    ports:
      - "6379:6379"
    restart: always
volumes:
  data: